FROM node:14 as dev

RUN mkdir /app
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
COPY next.config.js ./

RUN yarn install --frozen-lockfile
CMD ["yarn" , "dev"]

# [development] build and run:
# docker build -t holtzbin2dec-next:dev . -f .\Dockerfile.dev
# docker run -v ${PWD}:/app -v /app/node_modules -p 3001:3000 holtzbin2dec-next:dev
#
# or use docker-compose.dev.yml -> "docker-compose -f .\docker-compose.dev.yml up --build"