version: '3.8'

services:
  holtzbin2dec-nextjs:
    ports:
      - '3001:3000'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - holtzbin2dec-nextjs-dev-node_modules:/app/node_modules
      - holtzbin2dec-nextjs-dev-next:/app/.next
    restart: always

volumes:
  holtzbin2dec-nextjs-dev-node_modules:
  holtzbin2dec-nextjs-dev-next:
#docker-compose -f .\docker-compose.dev.yml up --build
